# Generated by Django 4.2.1 on 2023-07-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_company_isconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
