# Generated by Django 4.2.1 on 2023-07-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_company_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='stripe_customer_id',
        ),
    ]
